CREATE TABLE ${schemaName}.BG_REQUEST
(
    id                VARCHAR2(40) NOT NULL,
    request_id        VARCHAR2(40) NOT NULL UNIQUE,
    status            VARCHAR2(20),
    organisation_id   VARCHAR2(36),
    session_id        VARCHAR2(36),
    individual_id     VARCHAR2(36),
    bg_request        clob,
    pega_case_id      VARCHAR2(36),
    MASTER_REF_NUMBER VARCHAR2(40),
    TMS_CREATE        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CREATED_BY        VARCHAR2(36),
    TMS_UPDATE        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    UPDATED_BY        VARCHAR2(36),
    CONSTRAINT PK_BG_REQUEST PRIMARY KEY (id)
) TABLESPACE BGOS_AA;

CREATE TABLE ${schemaName}.DOCUMENTS
(
    id              VARCHAR2(40) NOT NULL,
    request_id      VARCHAR2(40) NOT NULL,
    doc_id          VARCHAR2(20),
    status          VARCHAR2(20),
    doc_type        VARCHAR2(20),
    organisation_id VARCHAR2(36),
    TMS_CREATE      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CREATED_BY      VARCHAR2(36),
    TMS_UPDATE      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    UPDATED_BY      VARCHAR2(36),
    CONSTRAINT PK_DOCUMENTS PRIMARY KEY (id),
    CONSTRAINT FK_BG_REQUEST FOREIGN KEY (request_id) REFERENCES ${schemaName}.BG_REQUEST (request_id)
) TABLESPACE BGOS_AA;

CREATE TABLE ${schemaName}.REPORTING
(
    id               VARCHAR2(40) NOT NULL,
    request_id       VARCHAR2(40) NOT NULL UNIQUE,
    reporting_status VARCHAR2(20),
    stp              VARCHAR2(20),
    TMS_CREATE       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    CREATED_BY       VARCHAR2(36),
    TMS_UPDATE       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    UPDATED_BY       VARCHAR2(36),
    CONSTRAINT PK_REPORTING PRIMARY KEY (id)
) TABLESPACE BGOS_AA;

CREATE TABLE ${schemaName}.SHEDLOCK
(
    name       VARCHAR2(64)  NOT NULL,
    lock_until TIMESTAMP    NOT NULL,
    locked_at  TIMESTAMP    NOT NULL,
    locked_by  VARCHAR2(255) NOT NULL,
    PRIMARY KEY (name)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON ${schemaName}.BG_REQUEST TO ROLE_BGOS_USER_NEW;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${schemaName}.DOCUMENTS TO ROLE_BGOS_USER_NEW;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${schemaName}.REPORTING TO ROLE_BGOS_USER_NEW;
GRANT SELECT, INSERT, UPDATE, DELETE ON ${schemaName}.SHEDLOCK TO ROLE_BGOS_USER_NEW;

CREATE PUBLIC SYNONYM BG_REQUEST FOR ${schemaName}.BG_REQUEST;
CREATE PUBLIC SYNONYM DOCUMENTS FOR ${schemaName}.DOCUMENTS;
CREATE PUBLIC SYNONYM REPORTING FOR ${schemaName}.REPORTING;
CREATE PUBLIC SYNONYM SHEDLOCK FOR ${schemaName}.SHEDLOCK;


