-- to be run manually under the PDBAdmin user
CREATE TABLESPACE BGOS_AA;
CREATE ROLE ROLE_BGOS_USER_NEW;
CREATE ROLE ROLE_BGOS_SCHEMA_OWNER;


GRANT CREATE TABLE to ROLE_BGOS_SCHEMA_OWNER;
GRANT CREATE MATERIALIZED VIEW to ROLE_BGOS_SCHEMA_OWNER;
GRANT CREATE TRIGGER to ROLE_BGOS_SCHEMA_OWNER;
GRANT CREATE PROCEDURE to ROLE_BGOS_SCHEMA_OWNER;
GRANT DROP PUBLIC SYNONYM to ROLE_BGOS_SCHEMA_OWNER;
GRANT CREATE SEQUENCE to ROLE_BGOS_SCHEMA_OWNER;
GRANT CREATE TYPE to ROLE_BGOS_SCHEMA_OWNER;
GRANT CREATE SESSION to ROLE_BGOS_SCHEMA_OWNER;
GRANT SELECT ANY TABLE to ROLE_BGOS_SCHEMA_OWNER;
GRANT CREATE VIEW to ROLE_BGOS_SCHEMA_OWNER;
GRANT CREATE PUBLIC SYNONYM to ROLE_BGOS_SCHEMA_OWNER;
GRANT GLOBAL QUERY REWRITE to ROLE_BGOS_SCHEMA_OWNER;


CREATE USER BGOS_OWNER IDENTIFIED BY "Instant123" DEFAULT TABLESPACE BGOS_AA TEMPORARY TABLESPACE TEMP PROFILE "C##ING_SERVICE_ACCOUNT" QUOTA UNLIMITED ON BGOS_AA;
GRANT ROLE_BGOS_SCHEMA_OWNER to BGOS_OWNER;


CREATE USER BGOS_USER_NEW IDENTIFIED BY "Instant123" DEFAULT TABLESPACE BGOS_AA TEMPORARY TABLESPACE TEMP PROFILE "C##ING_SERVICE_ACCOUNT" QUOTA UNLIMITED ON BGOS_AA;
GRANT CREATE SESSION to ROLE_BGOS_USER_NEW;
GRANT ROLE_BGOS_USER_NEW to BGOS_USER_NEW;


CREATE
    OR REPLACE TRIGGER BGOS_USER_NEW.set_schema
    AFTER logon
    ON BGOS_USER_NEW.schema
BEGIN
    execute immediate ('alter session set current_schema = BGOS_OWNER');
END;

