key_store_password: #{KEYSTORE-PASSWORD}#
key_password: #{KEY-PASSWORD}#
trust_store_password: #{TRUSTSTORE-PASSWORD}#
peer_token_password: #{PEER-TOKENS-KEYSTORE-PASSWORD}#
manifest_password: #{MANIFEST-TRUSTSTORE-PASSWORD}#
access_token_password: #{ACCESS-TOKENS-KEYSTORE-PASSWORD}#
DATABASE_USERNAME: #{BANKGUARANTEES-DB-USERNAME}#
DATABASE_USER_PASSWORD: #{BANKGUARANTEES-DB-USER-NEW-PASSWORD}#
BGOS-AUDIT-KEY: #{BGOS-AUDIT-KEY}#
ES-V2-PRODUCER-ENCRYPTION-KEY: #{ES-V2-PRODUCER-ENCRYPTION-KEY}#
ES-V2-CONSUMER-DECRYPTION-KEY: #{ES-V2-CONSUMER-DECRYPTION-KEY}#
DL-V2-PRODUCER-ENCRYPTION-KEY: #{DL-V2-PRODUCER-ENCRYPTION-KEY}#
ING-SIGNER-FIRST-CERTIFICATE: #{ING-SIGNER-FIRST-CERTIFICATE}#
ING-SIGNER-FIRST-PIN: #{ING-SIGNER-FIRST-PIN}#
ING-SIGNER-SECOND-CERTIFICATE: #{ING-SIGNER-SECOND-CERTIFICATE}#
ING-SIGNER-SECOND-PIN: #{ING-SIGNER-SECOND-PIN}#