service.name=BankGuaranteesBEOnline_API
server.port=8443
service.instance.datacenter=DCR
server.ssl.enabled=true
#server.ssl.keystore.type=PKCS12
#server.ssl.key-store=classpath:identity.p12
#server.ssl.key-store-password=${key_store_password}
#server.ssl.key-password=${key_password}
server.ssl.trust-store=classpath:http-trust.p12
server.ssl.trust-store.type=PKCS12
server.ssl.trust-store-password=${trust_store_password}
service.manifest.location=classpath:manifest.jose
service.manifest.trust-store.location=classpath:manifest.p12
service.manifest.trust-store.password=${manifest_password}


#ServiceDiscoveryConfiguration
servicediscovery.enabled=true
servicediscovery.seed-nodes=aed.test.eu.touchpoint.ing.net:18443
servicediscovery.registration.enabled=true



# Merak Http Client
merak.filter.deadline-filter.dark-mode=false
http-client.certificate-verification.environment.enabled=true
http-client.certificate-verification.service-name.enabled=true
http-client.routing-client.defaults.debugEnabled=true
http-client.routing-client.defaults.idempotent-requests.backup-requests-max-extra-load=0.05
http-client.routing-client.defaults.session.acquisition-timeout=5s
http-client.routing-client.defaults.certificate-verification.environment.enabled=true
http-client.routing-client.defaults.certificate-verification.service-name.enabled=true
http-client.routing-client.defaults.individual-request-timeout=10s
http-client.routing-client.defaults.global-request-timeout=10s
http-client.routing-client.defaults.debug-enabled=true
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/gcc/{repository}/{parenttype}/{parentid}/{objecttype}].backup-requests.max-extra-load=0
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/gcc/{repository}/{parenttype}/{parentid}/{objecttype}].individual-request-timeout=120s
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/gcc/{repository}/{parenttype}/{parentid}/{objecttype}].global-request-timeout=120s
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/gcc/{repository}/{objecttype}].backup-requests.max-extra-load=0
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/gcc/{repository}/{objecttype}].individual-request-timeout=120s
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/gcc/{repository}/{objecttype}].global-request-timeout=120s
http-client.routing-client.endpoints.[/endpoint/api.referencedata.ing.net/GET/v2/reference-data/multilingual/{tableDistributionName}].backup-requests.max-extra-load=0
http-client.routing-client.endpoints.[/endpoint/api.referencedata.ing.net/GET/v2/reference-data/multilingual/{tableDistributionName}].individual-request-timeout=120s
http-client.routing-client.endpoints.[/endpoint/api.referencedata.ing.net/GET/v2/reference-data/multilingual/{tableDistributionName}].global-request-timeout=120s
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/rtns/screen].individual-request-timeout=25s
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/rtns/screen].global-request-timeout=75s
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/sds-rt/credit-decision].individual-request-timeout=30s
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/sds-rt/credit-decision].global-request-timeout=75s
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/message/send/with-response].individual-request-timeout=75s
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/message/send/with-response].global-request-timeout=120s
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/prweb/PRRestService/TFSAppAPI/v1/cases].backup-requests.max-extra-load=0
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/prweb/PRRestService/TFSAppAPI/v1/cases].individual-request-timeout=75s
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/prweb/PRRestService/TFSAppAPI/v1/cases].global-request-timeout=120s
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/bank-guarantees/applications/intake].backup-requests.max-extra-load=0
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/bank-guarantees/applications/intake].individual-request-timeout=75s
http-client.routing-client.endpoints.[/endpoint/api.ing.com/POST/bank-guarantees/applications/intake].global-request-timeout=120s

#Upstream APIs details
rest.base.url=https://api.ing.com
rest.base.apis.url=https://apis.ing.com
rest.base.reference-data.url=https://api.referencedata.ing.net
rest.base.account-loan.url=https://klc.api.ing.com
rest.customerlending-api-creditlinearrangement-url=${rest.base.url}/api/klc/creditlinearrangement/update
rest.api-booking-loan-api-url=${rest.base.account-loan.url}/api/bookings
rest.delete.api-booking-loan-api-url=${rest.base.account-loan.url}/api/bookings/{id}
rest.account-loan-api-url=${rest.base.account-loan.url}/api/v2/account-loans/{contractNumber}
rest.master-api-reference-url=${rest.base.url}/v1/masterreference/branch/{branchId}/product/{productId}
rest.pega.create-case-url=${rest.base.url}/prweb/PRRestService/TFSAppAPI/v1/cases
rest.permission-api-involveparty-url=${rest.base.url}/v4/permissions/involved-parties/{id}
rest.permission-be-api-involveparty-url=${rest.base.url}/permissionbe/proxy/v4/permissions/involved-parties/{id}
rest.permission-api-productsagreements-url=${rest.base.url}/v4/permissions/agreements/products
rest.accountbalance-api-account-balance-Search-url=${rest.base.url}/api/accounts/balances/search
rest.customerlending-api-creditline-url=${rest.base.url}/api/lending/get/creditLineBalance
rest.credit-risk-api-credit-decision-url=${rest.base.url}/sds-rt/credit-decision
rest.csi-involved-party-retrieve-party-url=${rest.base.url}/csi/involved-party/retrieve-involved-party-details
rest.gcc.case-management.request-dossiers.url=${rest.base.url}/gcc/case-management/request-dossiers
rest.gcc.case-management.agreement-dossiers.url=${rest.base.url}/gcc/case-management/agreement-dossiers
rest.gcc.case-management.place-holder.documents.url=${rest.base.url}/gcc/case-management/agreement-dossiers/{dossier_id}/documents
rest.gcc.case-management.upload.documents.url=${rest.base.url}/gcc/case-management/documents/{documentId}?version=major
rest.gcc.case-management.document.content.url=${rest.base.url}/gcc/case-management/documents/{documentId}/content
rest.message.send.with-response.url=${rest.base.url}/message/send/with-response
rest.name-screening-detail-url=${rest.base.url}/rtns/screen
rest.pam-qualification-check.parties-url = ${rest.base.url}/api/qualification-checks/parties
rest.gar-collaterals.url=${rest.base.url}/api/gar/collateralstatement/docsimplification
rest.api-dar-document-sign.url=${rest.base.url}/docsign/v2/document-action-requests
rest.api-dar-document-v3-sign.url=${rest.base.url}/docsign/v3/document-action-requests
rest.api-cla-fund-reservation.url=${rest.base.url}/api/fund-reservation
rest.common-core-api.update-dossier-path=${rest.base.url}/gcc/case-management/{dossierType}/{dossierId}
rest.bank-account-number-api-single-get-url=${rest.base.url}/bankaccountnumbers/single/get
rest.active-bank-guarantees.intake.url=${rest.base.url}/bank-guarantees/applications/intake
rest.gess.pkbox.esign.url=${rest.base.url}/pkbox/esign
rest.customer-arrangement-detail.url=${rest.base.url}/api/arrangement-reporting/customer-arrangement-details
rest.representation-management-be.retrieve-signatories.url=${rest.base.url}/representation-management-be/retrieve-signatories
rest.payments.forex.emea.generic-rates.convert.url=${rest.base.url}/payments/forex/emea/generic-rates/convert

rest.involved-party-details-url=${rest.base.apis.url}/v6/involved-parties/{uuid}
rest.involved-party-grantees-details-url=${rest.base.apis.url}/v5/involved-parties/{uuid}/grantees
rest.involved-party-external-identifiers-url=${rest.base.apis.url}/v5/involved-parties/{uuid}/external-identifiers
rest.product-agreement.url=${rest.base.apis.url}/v6/agreements/products

rest.reference-data.multilingual.ctry-api-url=${rest.base.reference-data.url}/v2/reference-data/multilingual/{tableDistributionName}
rest.reference-data.attribute.ctry-api-url=${rest.base.reference-data.url}/v2/reference-data/attributes/{tableDistributionName}
rest.reference-data.attribute.holidays-url=${rest.base.reference-data.url}/holidays/{center}

#Kafka Properties
spring.kafka.client-id=BankGuaranteeOnlineWebServiceNotifications
spring.kafka.bootstrap-servers=br101-odin-tst.ic.ing.net:9093, br201-odin-tst.ic.ing.net:9093, br301-odin-tst.ic.ing.net:9093, br401-odin-tst.ic.ing.net:9093

spring.kafka.properties.ssl.truststore.location=/certs/http-trust.p12
spring.kafka.properties.ssl.truststore.password=${trust_store_password}
spring.kafka.properties.ssl.truststore.type=PKCS12
spring.kafka.properties.ssl.keystore.location=/certs/identity.p12
spring.kafka.properties.ssl.keystore.password=${key_store_password}
spring.kafka.properties.ssl.key.password=${key_password}
spring.kafka.properties.ssl.keystore.type=PKCS12
spring.kafka.properties.security.protocol=SSL
spring.kafka.properties.ssl.enabled.protocols=TLSv1.2
spring.kafka.properties.schema.registry.ssl.enabled.protocols=TLSv1.2
spring.kafka.properties.schema.registry.ssl.protocol=TLSv1.2

spring.kafka.properties.schema.registry.url=https://sr1-global-tst.ing.net:8443,https://sr2-global-tst.ing.net:8443
spring.kafka.properties.schema.registry.ssl.keystore.location=/certs/identity.p12
spring.kafka.properties.schema.registry.ssl.keystore.password=${key_store_password}
spring.kafka.properties.schema.registry.ssl.key.password=${key_password}
spring.kafka.properties.schema.registry.ssl.keystore.type=PKCS12
spring.kafka.properties.schema.registry.ssl.truststore.location=/certs/http-trust.p12
spring.kafka.properties.schema.registry.ssl.truststore.password=${trust_store_password}
spring.kafka.properties.schema.registry.ssl.truststore.type=PKCS12

spring.kafka.properties.specific.avro.reader=true
spring.kafka.properties.auto.register.schemas=false
spring.kafka.producer.acks=all
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=com.ing.apisdk.toolkit.connectivity.kafka.avro.serde.EncryptingKafkaPayloadAvroSerializer
spring.kafka.producer.properties.value.ing.serde.avro.sharedsecret=${ES-V2-PRODUCER-ENCRYPTION-KEY}
spring.kafka.consumer.properties.specific.avro.reader=true
spring.kafka.consumer.key-deserializer= org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer= com.ing.apisdk.toolkit.connectivity.kafka.avro.serde.DecryptingKafkaPayloadAvroDeserializer
spring.kafka.consumer.properties.value.ing.serde.avro.sharedsecret=${ES-V2-CONSUMER-DECRYPTION-KEY}


#Merak Filter
merak.filter.peer-token-filter.enabled=false
merak.filter.local-peer-token-filter.enabled=false
merak.filter.local-access-token-filter.enabled=false

#Tracing
merak.tracing.reporting.kafka.enabled=true
merak.tracing.reporting.kafka.connectionString=br201-hulk-tst.ic.ing.net:9093,br401-hulk-tst.ic.ing.net:9093


#Centralized logging
merak.logging.kafka.enabled=true
merak.logging.kafka.topic=log_bgo_tech_topic
merak.application.name=${service.name}
merak.logging.kafka.formatted-message=true
merak.logging.kafka.tls-enabled=true
merak.logging.kafka.connection-string=br201-hulk-tst.ic.ing.net:9093,br401-hulk-tst.ic.ing.net:9093
#merak.logging.kafka.ssl.keystore-location=classpath:identity.p12
#merak.logging.kafka.ssl.key-store-type=PKCS12
#merak.logging.kafka.ssl.keystore-password=${key_store_password}

merak.logging.kafka.c3.enabled=true
merak.logging.kafka.c3.encryption-key=${BGOS-AUDIT-KEY}
merak.logging.kafka.c3.topic=log_bgo_audit_topic
merak.insights.kafka.enabled=false
merak.sema.kafka.enabled=true

merak.application.ing-identifier=e479b90d3b475650b24e282a85e45a00
merak.application.country-code=BE
merak.application.purpose-code=P31464
merak.application.cmdb-id=7c2b3611339e5e9019a782934d5c7ba2


api-trust-tokens.access-tokens.keystore.location=classpath:accesstokens.p12
api-trust-tokens.access-tokens.keystore.password=${access_token_password}
api-trust-tokens.peer-tokens.keystore.location=classpath:peertokens.p12
api-trust-tokens.peer-tokens.keystore.password=${peer_token_password}

logging.level.root=INFO
logging.level.com.ing.apisdk.toolkit.connectivity.discovery.phoenix=INFO
logging.level.com.ing.baker=INFO
logging.level.com.ing.onboardbe=INFO
logging.level.org.apache.kafka.clients=INFO
logging.level.com.ing.apisdk.toolkit.service.internal.OperationalModeWatchService=INFO


#warmup
warmup.enabled=false
merak.access-token.person-identifier.enabled=true
merak.access-token.identifying-attributes.enabled=true
logging.level.com.ing.bb=INFO
logging.level.com.twitter.finagle=INFO


#Database config
spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(CONNECT_TIMEOUT=30)(RETRY_COUNT=20)(RETRY_DELAY=3)(ADDRESS_LIST=(LOAD_BALANCE=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=xbi317-scan.dbaas.ing.net)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=bankguaranteestst_23470_ac_dbaas)))
spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_USER_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database=oracle
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=none



# Products
bgos.account-balance.currencies.3=EUR
bgos.account-balance.default-currency-code=003
bgos.account-balance.default-product-id=000
bgos.service-name=BankGuaranteesBEOnline_API
bgos.default.currencies.3=EUR
bgos.default-currency-code=003
bgos.default-country-code=BE
bgos.errors.input-file-path=errors/%s_errors.json
bgos.bank-guarantee-types.input-file-path=bankguarantee/bank_guarantee_data.json
bgos.orf-application-url=http://acc.promo.ing.be/bankguarantees/index.aspx?ID=lq4ltZ6FRvja_GD%2BTUwwVGqHF%2Bre6hkHmEGA0mlLr_NjizEqLH%2BwQDhg8UWnUmF6yqWg6eCCkiGsl0&TYPE=<TYPE_NUMBER>
bgos.bank-guarantee-application-url=https://acc.promo.ing.be/banking/bankguarantee
bgos.currencies.input-file-path=currency/currency.json
bgos.credit-decision.mock=true
bgos.name-screening.mock=true
bgos.reserve-fund=false
bgos.docsign-signingmean=SES
bgos.saac.significance-type=informational
bgos.service-activity-type=involved-parties:bank-guarantees:create
bgos.dossier-url=https://test.dcs-viewer.ing.net/
bgos.app.env=TST

# merak administration: https://theforge.ing.net/product/12051/documentation/19.1.2/merak/reference.html#administration-server
merak.administration.metrics.enabled=true
merak.administration.metrics.jvm-metrics-enabled=true
merak.administration.metrics.publish-enabled=true
merak.administration.server.bind-host=0.0.0.0
merak.administration.server.bind-port=10080

management.server.address=0.0.0.0

bgos.ing.signer.config.first.certificate-id=${ING-SIGNER-FIRST-CERTIFICATE}
bgos.ing.signer.config.first.pin=${ING-SIGNER-FIRST-PIN}
bgos.ing.signer.config.second.certificate-id=${ING-SIGNER-SECOND-CERTIFICATE}
bgos.ing.signer.config.second.pin=${ING-SIGNER-SECOND-PIN}

# Data Lake config=#
data-lake-event.topic=ing_Aurora_bankguarantee_application
data-lake-event.shared-secret=${DL-V2-PRODUCER-ENCRYPTION-KEY}
data-lake-event.client-id=BankGuaranteesBeOnlineServicesNotifications
