/*
 * Bank GuaranteesBEOnline API
 * This API manages is to create Bank Guarantees via Oneweb/Oneapp channels
 *
 * The version of the OpenAPI document: 15.0.0
 * Contact: BankGuarantee-STP@ing.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ing.bankguarantees.models.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BankGuaranteeCodeSetResponse {

    private List<BankGuaranteeCodeResponse> codes;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class BankGuaranteeCodeResponse {

        private String code;

        private String bgType;

        private String bgSubType;
    }
}

