api-trust-tokens.access-tokens.keystore.location=/keystores/accesstokens.jks
api-trust-tokens.access-tokens.keystore.password=publicpass
api-trust-tokens.access-tokens.signature.key.certificate-fingerprint=73:1D:13:B1:91:5B:B4:86:72:23:A7:FC:00:C1:0F:0D:B2:EF:81:7F
api-trust-tokens.access-tokens.signature.key.password=publicpass