<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>BankGuaranteesBEOnline_API</artifactId>
        <groupId>com.ing.bankguarantees</groupId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>conf</artifactId>
    <name>conf</name>
    <packaging>pom</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>assemble-config-zips</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <appendAssemblyId>true</appendAssemblyId>
                            <descriptors>
                                <descriptor>src/assembly/ichp-tst-dcr.xml</descriptor>
                                <descriptor>src/assembly/ichp-acc-dcr.xml</descriptor>
                                <descriptor>src/assembly/ichp-acc-wpr.xml</descriptor>
                                <descriptor>src/assembly/ichp-prd-dcr.xml</descriptor>
                                <descriptor>src/assembly/ichp-prd-wpr.xml</descriptor>
                            </descriptors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>