/*
 * CustomerLendingArrangements API
 * CustomerLendingArranagements API retrieves the list of lending arrangements for a specified borrower or for a group, and for a specified credit mode/product (if specified). This API calls KGCLBC and CREISG easy reqkeys to get the lending arrangements.
 *
 * The version of the OpenAPI document: 9.0.3
 * Contact: API_Lending_Support@ing.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ing.bankguarantees.remote.rest.cla.creditlinebalance.model.response;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.List;


/**
 * CreditLineBalanceResponse
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CreditLineBalanceResponse {

    @NotNull
    private List<CreditDetailsResponse> contractDetails;

    @Builder
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class CreditDetailsResponse {

        @NotNull
        private BigDecimal contractNumber;
        private AvailableAmountResponse availableAmount;
        private String endDate;
        private Integer productCode;
        private Integer rangeStatus;

    }

    @Builder
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class AvailableAmountResponse {

        @NotBlank
        private String currency;

        @NotNull
        private BigDecimal amount;
        private Integer decimal;

    }


}

