server.port=8443
service.name=BankGuaranteesBEOnline_API
service.instance.datacenter=WPR
service.instance.operational-mode.default-mode=live
service.instance.operational-mode.file.location=classpath:operationalmode
service.instance.operational-mode.file.interval=500
service.manifest.location=classpath:BankGuaranteesBEOnline_API.jose
service.manifest.trust-store.password=publicpass
service.manifest.trust-store.location=classpath:manifest.p12
servicediscovery.enabled=false
servicediscovery.registration.enabled=false

# Mutual TLS Configuration
server.ssl.key-store=classpath:keystore.p12
server.ssl.trust-store=classpath:http-trust.p12
server.ssl.key-store-type=PKCS12
server.ssl.trust-store-type=PKCS12
server.ssl.key-store-password=publicpass
server.ssl.key-password=publicpass
server.ssl.trust-store-password=publicpass
server.ssl.key-alias=1
#server.ssl.client-auth=none

merak.application.name=${service.name}
merak.application.ing-identifier=e269ba95335e5e9019a782934d5c7b8e
merak.application.country-code=BE
merak.tracing.reporting.kafka.enabled=false
merak.logging.kafka.enabled=false
merak.logging.kafka.topic=log_bgo_tech_topic
merak.logging.kafka.formatted-message=true
merak.logging.kafka.ssl.keystore-location=classpath:identity.p12
merak.logging.kafka.ssl.key-store-type=PKCS12
merak.logging.kafka.ssl.truststore-location=classpath:truststore.p12
merak.logging.kafka.ssl.trust-store-type=PKCS12
merak.logging.kafka.ssl.keystore-password=publicpass
merak.logging.kafka.ssl.truststore-password=publicpass
merak.logging.kafka.c3.enabled=true
merak.logging.kafka.c3.encryption-key=publicpass
merak.logging.kafka.c3.topic=log_bgo_audit_topic
merak.application.cmdb-id=7c2b3611339e5e9019a782934d5c7ba2
merak.insights.kafka.enabled=false
merak.application.purpose-code=P31464
logging.level.root=INFO
logging.level.com.ing.bankguarantees=INFO
logging.level.com.twitter.finagle=INFO

# Merak Http Client
http-client.certificate-verification.environment.enabled=true
http-client.certificate-verification.service-name.enabled=true
http-client.routing-client.defaults.debugEnabled=true
http-client.routing-client.defaults.idempotent-requests.backup-requests-max-extra-load=0.05
http-client.routing-client.defaults.session.acquisition-timeout=5s
http-client.routing-client.defaults.certificate-verification.environment.enabled=true
http-client.routing-client.defaults.certificate-verification.service-name.enabled=true
http-client.routing-client.defaults.individual-request-timeout=10s
http-client.routing-client.defaults.global-request-timeout=10s
http-client.routing-client.defaults.debug-enabled=true

#Upstream APIs details
rest.base.url=https://api.ing.com
rest.base.apis.url=https://apis.ing.com
rest.base.reference-data.url=https://api.referencedata.ing.net
rest.base.account-loan.url=https://klc.api.ing.com
rest.customerlending-api-creditlinearrangement-url=${rest.base.url}/api/klc/creditlinearrangement/update
rest.api-booking-loan-api-url=${rest.base.account-loan.url}/api/bookings
rest.delete.api-booking-loan-api-url=${rest.base.account-loan.url}/api/bookings/{id}
rest.account-loan-api-url=${rest.base.account-loan.url}/api/v2/account-loans/{contractNumber}
rest.pega.create-case-url=${rest.base.url}/prweb/PRRestService/TFSAppAPI/v1/cases
rest.master-api-reference-url=${rest.base.url}/v1/masterreference/branch/{branchId}/product/{productId}
rest.permission-api-involveparty-url=${rest.base.url}/v4/permissions/involved-parties/{id}
rest.permission-be-api-involveparty-url=${rest.base.url}/permissionbe/proxy/v4/permissions/involved-parties/{id}
rest.permission-api-productsagreements-url=${rest.base.url}/v4/permissions/agreements/products
rest.accountbalance-api-account-balance-Search-url=${rest.base.url}/api/accounts/balances/search
rest.customerlending-api-creditline-url=${rest.base.url}/api/lending/get/creditLineBalance
rest.credit-risk-api-credit-decision-url=${rest.base.url}/sds-rt/credit-decision
rest.csi-involved-party-retrieve-party-url=${rest.base.url}/csi/involved-party/retrieve-involved-party-details
rest.gcc.case-management.request-dossiers.url=${rest.base.url}/gcc/case-management/request-dossiers
rest.gcc.case-management.agreement-dossiers.url=${rest.base.url}/gcc/case-management/agreement-dossiers
rest.gcc.case-management.place-holder.documents.url=${rest.base.url}/gcc/case-management/agreement-dossiers/{dossier_id}/documents
rest.gcc.case-management.upload.documents.url=${rest.base.url}/gcc/case-management/documents/{documentId}?version=major
rest.gcc.case-management.document.content.url=${rest.base.url}/gcc/case-management/documents/{documentId}/content
rest.message.send.with-response.url=${rest.base.url}/message/send/with-response
rest.name-screening-detail-url=${rest.base.url}/rtns/screen
rest.pam-qualification-check.parties-url = ${rest.base.url}/api/qualification-checks/parties
rest.gar-collaterals.url=${rest.base.url}/api/gar/collateralstatement/docsimplification
rest.api-dar-document-sign.url=${rest.base.url}/docsign/v2/document-action-requests
rest.api-dar-document-v3-sign.url=${rest.base.url}/docsign/v3/document-action-requests
rest.api-cla-fund-reservation.url=${rest.base.url}/api/fund-reservation
rest.common-core-api.update-dossier-path=${rest.base.url}/gcc/case-management/{dossierType}/{dossierId}
rest.bank-account-number-api-single-get-url=${rest.base.url}/bankaccountnumbers/single/get
rest.active-bank-guarantees.intake.url=${rest.base.url}/bank-guarantees/applications/intake
rest.gess.pkbox.esign.url=${rest.base.url}/pkbox/esign
rest.customer-arrangement-detail.url=${rest.base.url}/api/arrangement-reporting/customer-arrangement-details
rest.representation-management-be.retrieve-signatories.url=${rest.base.url}/representation-management-be/retrieve-signatories
rest.payments.forex.emea.generic-rates.convert.url=${rest.base.url}/payments/forex/emea/generic-rates/convert
rest.involved-party-details-url=${rest.base.apis.url}/v6/involved-parties/{uuid}
rest.involved-party-grantees-details-url=${rest.base.apis.url}/v5/involved-parties/{uuid}/grantees
rest.involved-party-external-identifiers-url=${rest.base.apis.url}/v5/involved-parties/{uuid}/external-identifiers
rest.product-agreement.url=${rest.base.apis.url}/v6/agreements/products
rest.reference-data.multilingual.ctry-api-url=${rest.base.reference-data.url}/v2/reference-data/multilingual/{tableDistributionName}
rest.reference-data.attribute.ctry-api-url=${rest.base.reference-data.url}/v2/reference-data/attributes/{tableDistributionName}
rest.reference-data.attribute.holidays-url=${rest.base.reference-data.url}/holidays/{center}

#Kafka Properties#
spring.kafka.client-id=BankGuaranteeOnlineWebServiceNotifications
spring.kafka.bootstrap-servers=br201-odin-dev.ic.ing.net:9093, br401-odin-dev.ic.ing.net:9093
spring.kafka.listener.missing-topics-fatal=true
spring.kafka.properties.security.protocol=SSL
spring.kafka.properties.specific.avro.reader=true
spring.kafka.properties.auto.register.schemas=false
spring.kafka.producer.acks=all
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=com.ing.apisdk.toolkit.connectivity.kafka.avro.serde.EncryptingKafkaPayloadAvroSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=com.ing.apisdk.toolkit.connectivity.kafka.avro.serde.DecryptingKafkaPayloadAvroDeserializer
spring.kafka.properties.ssl.truststore.location=${user.dir}\\..\\conf\\src\\main\\local\\http-trust.p12
spring.kafka.properties.ssl.truststore.password=publicpass
spring.kafka.properties.ssl.truststore.type=PKCS12
spring.kafka.properties.ssl.keystore.location=${user.dir}\\..\\conf\\src\\main\\local\\keystore.p12
spring.kafka.properties.ssl.keystore.password=publicpass
spring.kafka.properties.ssl.key.password=publicpass
spring.kafka.properties.ssl.keystore.type=PKCS12
spring.kafka.consumer.properties.specific.avro.reader=true
spring.kafka.producer.properties.value.ing.serde.avro.sharedsecret=2CFD1DF444796AAD89D465393D0B265AE5523B7A839627A651C7585338B5004B
spring.kafka.consumer.properties.value.ing.serde.avro.sharedsecret=32BA74361EE73B3CE9DBFFCD93AEF150D99B69A6C4DFDDC9077922A0143F6301

spring.kafka.properties.schema.registry.url=https://sr1-global-dev.ing.net:8443, https://sr2-global-dev.ing.net:8443
spring.kafka.properties.schema.registry.ssl.keystore.location=${user.dir}\\..\\conf\\src\\main\\local\\keystore.p12
spring.kafka.properties.schema.registry.ssl.keystore.password=publicpass
spring.kafka.properties.schema.registry.ssl.key.password=publicpass
spring.kafka.properties.schema.registry.ssl.keystore.type=PKCS12
spring.kafka.properties.schema.registry.ssl.truststore.location=${user.dir}\\..\\conf\\src\\main\\local\\http-trust.p12
spring.kafka.properties.schema.registry.ssl.truststore.password=publicpass
spring.kafka.properties.schema.registry.ssl.truststore.type=PKCS12

# Data Lake config #
data-lake-event.topic=ing_Aurora_bankguarantee_application
data-lake-event.shared-secret=62B0E322324D0868DB5C98D1709F3B62AFA1E2ECF9C3079EA4BA604638685085
data-lake-event.client-id=BankGuaranteesBeOnlineServicesNotifications


#Merak Sema Kafka Properties
merak.sema.kafka.enabled=false
merak.sema.kafka.tls-enabled=false
merak.sema.kafka.use-schema-registry=true
merak.sema.kafka.connectionString=http://localhost:9092
merak.sema.kafka.schema-registry-url=http://localhost:8081
merak.sema.kafka.ext.auto.register.schemas=true


# API trust - Access Token
merak.filter.deadline-filter.enabled=true
merak.filter.deadline-filter.dark-mode=false
merak.filter.peer-token-filter.enabled=false
merak.filter.access-token-filter.enabled=true
merak.filter.headerforwarder.enabled=false

api-trust-tokens.access-tokens.keystore.location=classpath:accesstokens.p12
api-trust-tokens.access-tokens.keystore.password=publicpass
api-trust-tokens.peer-tokens.keystore.location=classpath:peertokens.p12
api-trust-tokens.peer-tokens.keystore.password=publicpass


# Spring Defaults
spring.application.name=${service.name}
spring.mvc.main.allow-bean-definition-overriding=true
spring.mvc.async.request-timeout=-1

#warmup
warmup.enabled=false


# Prometheus metrics
management.server.address=0.0.0.0

# Local Oracle Database
spring.datasource.url=jdbc:h2:mem:testdb;Mode=Oracle;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:scripts/create.sql'
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.database=h2
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.h2.console.settings.web-allow-others=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Products
bgos.account-balance.currencies.3=EUR
bgos.account-balance.default-currency-code=003
bgos.account-balance.default-product-id=000
bgos.service-name=BankGuaranteesBEOnline_API
bgos.default.currencies.3=EUR
bgos.default-currency-code=003
bgos.default-country-code=BE
bgos.errors.input-file-path=errors/%s_errors.json
bgos.bank-guarantee-types.input-file-path=bankguarantee/bank_guarantee_data.json
bgos.orf-application-url=http://acc.promo.ing.be/bankguarantees/index.aspx?ID=lq4ltZ6FRvja_GD%2BTUwwVGqHF%2Bre6hkHmEGA0mlLr_NjizEqLH%2BwQDhg8UWnUmF6yqWg6eCCkiGsl0&TYPE=<TYPE_NUMBER>
bgos.bank-guarantee-application-url=https://acc.promo.ing.be/banking/bankguarantee
bgos.currencies.input-file-path=currency/currency.json
bgos.credit-decision.mock=false
bgos.name-screening.mock=false
bgos.reserve-fund=false
bgos.docsign-signingmean=SES
bgos.saac.significance-type=informational
bgos.service-activity-type=involved-parties:bank-guarantees:create
bgos.dossier-url=https://test.dcs-viewer.ing.net/
bgos.app.env=LOCAL


bgos.ing.signer.config.first.certificate-id=SEAL_27699_SIGN_1761211181608
bgos.ing.signer.config.first.pin=111111
bgos.ing.signer.config.second.certificate-id=SEAL_29515_SIGN_1761211406111
bgos.ing.signer.config.second.pin=987654321


merak.filter.local-peer-token-filter.enabled:false
merak.filter.local-access-token-filter.enabled:false
