package com.ing.bankguarantees.error.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * Type of {@link BgosException}
 */
@Getter
@RequiredArgsConstructor
public enum ErrorCode {


    NOT_FOUND("BGOS-00-000"),

    TECHNICAL_ERROR("BGOS-00-001"),

    INVALID_RESPONSE_FROM_CLIENT("BGOS-00-002"),

    INVALID_REQUEST("BGOS-00-003"),

    PERMISSION_DENIED("BGOS-00-004"),

    CLIENT_NOT_ELIGIBLE("BGOS-00-005"),

    INVALID_ACCESS_TOKEN("BGOS-00-006"),

    ENTITY_NOT_FOUND("BGOS-00-007"),

    INVALID_LEGAL_REP("BGOS-00-008"),

    INC_ADDRESS_NOT_FOUND("BGOS-00-009"),

    INC_ORG_NAME_NOT_FOUND("BGOS-00-010"),

    INVALID_ACCOUNT("BGOS-00-011"),

    INVALID_CREDIT_LINE_ACCOUNT("BGOS-00-012"),

    PDF_READ_ERROR("BGOS-00-013"),

    REQUESTID_NOT_FOUND("BGOS-00-014"),

    UNSUPPORTED_BANK_GUARANTEE("BGOS-00-015"),

    INVALID_COUNTRY("BGOS-00-016"),

    INVALID_CURRENCY("BGOS-00-017"),

    INVALID_SIGNER_COUNT("BGOS-00-018"),

    INVALID_SIGNER("BGOS-00-019"),

    CURRENT_ACCOUNT_NOT_FOUND("BGOS-00-020"),

    INVALID_REQUESTER("BGOS-00-021"),

    DOCUMENT_NOT_READY("BGOS-00-022"),

    DOCUMENT_CREATION_FAILED("BGOS-00-023"),

    DEFAULT_BENEFICIARY_NOT_FOUND("BGOS-00-024"),

    REQUESTER_IS_NOT_SIGNER("BGOS-00-025"),

    INVALID_UPLOAD_BG_TYPE("BGOS-00-026"),

    INVALID_CUSTOM_DOC_DETAILS("BGOS-00-027");

    private final String code;
}