/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.ing.bankguarantees.remote.kafka.engagementsuite.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Source {

    /**
     * The source hostname of the message producer
     */
    private String hostname;
    /**
     * The unique identifier of the source instance
     */
    private String instanceId;

}










