package com.ing.bankguarantees.remote.kafka.engagementsuite.model;


public enum SupportedCommunication {
    NON_STP_EMAIL_NOTIFICATION,
    CUSTOMER_EMAIL_NOTIFICATION,
    BENEFICIARY_EMAIL_NOTIFICATION,
    FULFILMENT_FAILURE_EMAIL_NOTIFICATION,
    STP_RESULTS_EMAIL_NOTIFICATION,
    SIGN_COMPLETION_EMAIL_NOTIFICATION,
    SIGNATURE_REMINDER_EMAIL_NOTIFICATION,
    REQUESTER_PARTIALLY_SIGN_EMAIL_NOTIFICATION,
}
